BookMyTickets/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace BookMyTickets.Models
{
    public class User
    {
        [Key]
        public int UserId { get; set; }

       
        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name is required.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Invalid First Name.")]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

      
        [Required(AllowEmptyStrings = false, ErrorMessage = "Last Name is required.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Invalid Last Name.")]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required]
      
        public string UserName { get; set; }
        
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required.")]
        [DisplayName("Password")]
        public string Password { get; set; }

      
        public string Gender { get; set; }
       
        [Required]
        [DisplayName("Mobile No")]
        public string MobileNo { get; set; }


        [DataType(DataType.EmailAddress)]
        [DisplayName("Email")]
        public string Email { get; set; }

        public string Address { get; set; }
        

        public string role { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }

    }
}

BookMyTickets/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookMyTickets.Models;
using System.Data;
using Microsoft.AspNetCore.Http;


namespace BookMyTickets.Controllers
{
    public class UsersController : Controller
    {
        private readonly AppDbContext _context;
        

        public UsersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(User user)
        {
            var userDetails = _context.Users.Where(x => x.Email == user.Email).FirstOrDefault();
            var phone = _context.Users.Where(x => x.Email == user.Email).FirstOrDefault();
            if (userDetails == null)
            {
                if (phone == null)
                {
                    if (ModelState.IsValid)
                    {
                        user.role = "client";
                        _context.Add(user);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(SignInForUser));
                    }
                    return View(user);
                }
                else
                {
                    ModelState.AddModelError("", "Phone number already Exist");
                    return View("Create");
                }
            }
            else
            {
                ModelState.AddModelError("", "Email already Exist");
                return View("Create");
            }
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,FirstName,LastName,UserName,Password,Gender,MobileNo,Email,Address")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Profile));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }

        [HttpGet]
        public IActionResult SignInForUser()
        {
            HttpContext.Session.SetString("UserName", "");
            return View();
        }

        [HttpPost]
        public IActionResult SignInForUser(User user)
        {

                var userDetails = _context.Users.Where(x => x.Email == user.Email && x.Password == user.Password).FirstOrDefault();

                if (userDetails == null)
                {
                    ModelState.AddModelError("", "Invalid UserName or Password");
                    return View("SignInForUser");
                }
                else
                {
                    if (userDetails.role == "Admin")
                    {
                        HttpContext.Session.SetString("UserName", "Admin");
                        return RedirectToAction("Index", "Home");
                    }
                    HttpContext.Session.SetString("UserName", userDetails.UserName);
                    //HttpContext.Session.SetString("UserId", userDetails.UserId );
                    return RedirectToAction("Index", "Home");
                }
            
        }

        public IActionResult LogOutForUser()
        {
            HttpContext.Session.SetString("UserName", "" );
            return View("SignInForUser");
        }

        public IActionResult Profile()
        {
            var user = _context.Users.FirstOrDefault(x => x.UserName == HttpContext.Session.GetString("UserName"));
            return View("Details",user);
        }

    }
}

BookMyTickets/Views/Users/Create.cshtml
@model BookMyTickets.Models.User

@{
    ViewData["Title"] = "Create";
}
    <style>
        .signup {
            box-shadow: 5px 15px rgb(203, 221, 236);
            background-color: rgb(205, 247, 247);
            display: flex;
            flex-direction: column;
            margin: 50px;
            margin-left: 30%;
            margin-right: 30%;
            padding: 50px;
            border-radius: 20px;
            border: none;
            height: auto;
        }
    </style>
    <div class="signup">
        <h2>SignUp For Customer</h2>
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserName" class="control-label"></label>
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <input asp-for="Gender" class="form-control" />
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MobileNo" class="control-label"></label>
                        <input asp-for="MobileNo" class="form-control" />
                        <span asp-validation-for="MobileNo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                        <a href="C:\Users\moe\Desktop\Project_CE032-master\Project_CE032-master\BookMyTickets\BookMyTickets\Controllers\QueriesController.cs">C:\Users\moe\Desktop\Project_CE032-master\Project_CE032-master\BookMyTickets\BookMyTickets\Controllers\QueriesController.cs</a>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="SignUp For Customer" class="btn btn-primary" />
                        <a style="margin-left:auto" class="btn btn-primary" name=" value="Go To Login" asp-controller="Users" asp-action="SignInForUser">Go To Login</a>
                    </div>

                </form>
    </div>
   

BookMyTickets/Views/Users/Delete.cshtml
@model BookMyTickets.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MobileNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookMyTickets/Views/Users/Details.cshtml
@model BookMyTickets.Models.User

@{
    ViewData["Title"] = "Details";
}

<style>
    #navProfile{
        background-color:aliceblue;
    }
</style>

<h2>Your Profile</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MobileNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
</div>
<div>
    <h1><a asp-action="Edit"  asp-route-id="@Model.UserId" class="btn-primary" >Edit</a></h1> 
  
</div>

BookMyTickets/Views/Users/Edit.cshtml
@model BookMyTickets.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobileNo" class="control-label"></label>
                <input asp-for="MobileNo" class="form-control" />
                <span asp-validation-for="MobileNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BookMyTickets/Views/Users/Index.cshtml
@model IEnumerable<BookMyTickets.Models.User>

@{
    ViewData["Title"] = "Index";
}
    <style>
        #seeAllUsers{
            background-color:aliceblue;
        }
    </style>

    <h2>
        List Of All the Users
    </h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MobileNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.UserId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.UserId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.UserId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BookMyTickets/Views/Users/SignInForUser.cshtml
@model User

@{
    ViewData["Title"] = "SignInForUser";
}
<style>
    @*#navSignInForCustomer {
        background-color: aliceblue;
    }

    .loginBox {
        box-shadow: 5px 15px rgb(203, 221, 236);
        background-color: rgb(205, 247, 247);
        display: flex;
        flex-direction: column;
        margin: 5rem;
        margin-left: 30%;
        margin-right: 30%;
        padding: 50px;
        border-radius: 20px;
        border: none;
        height: auto;
        font-size: medium;
    }*@
</style>

<div class="loginBox ">
    <form action="# " method="POST" id="login-form ">
        <div>
            <h1>Login</h1>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-15">
            <input class="form-control text-box single-line" data-val="true" data-val-required="Password is required." id="Password" name="Password" type="password" value="">
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
   
        <div class="form-group" id="signupLink"><a asp-action="Create" asp-controller="Users">New User!!Click Here For Registration</a></div>
        <div class="form-group" id="submit"><button type="submit" class="btn btn-primary">Login</button></div>
    </form>
</div>