BookMyTickets/Models/Theater.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookMyTickets.Models
{
    public class Theater
    {
        [Key]
        public int TheaterId { get; set; }

        [Required]
        public string TheaterName { get; set; }

        [Required]
        public string City { get; set; }

      
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required.")]
        public string Password { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Email is required.")]
        public string Email { get; set; }


        [Required]
        public string Address { get; set; }

        public int NoOfScreen { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Show> Shows { get; set; }

    }
}

BookMyTickets/Controllers/TheatersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookMyTickets.Models;
using System.Data;
using Microsoft.AspNetCore.Http;

namespace BookMyTickets.Controllers
{
    public class TheatersController : Controller
    {
        private readonly AppDbContext _context;

        public TheatersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Theaters
        public async Task<IActionResult> Index()
        {
            return View(await _context.Theaters.ToListAsync());
        }

        // GET: Theaters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theater = await _context.Theaters
                .FirstOrDefaultAsync(m => m.TheaterId == id);
            if (theater == null)
            {
                return NotFound();
            }

            return View(theater);
        }

        // GET: Theaters/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Theaters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TheaterId,TheaterName,City,Password,Email,Address,NoOfScreen")] Theater theater)
        {
            if (ModelState.IsValid)
            {
                _context.Add(theater);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(SignInForTheater));
            }
            return View(theater);
        }

        // GET: Theaters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theater = await _context.Theaters.FindAsync(id);
            if (theater == null)
            {
                return NotFound();
            }
            return View(theater);
        }

        // POST: Theaters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TheaterId,TheaterName,City,Password,Email,Address,NoOfScreen")] Theater theater)
        {
            if (id != theater.TheaterId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(theater);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TheaterExists(theater.TheaterId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(theater);
        }

        // GET: Theaters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var theater = await _context.Theaters
                .FirstOrDefaultAsync(m => m.TheaterId == id);
            if (theater == null)
            {
                return NotFound();
            }

            return View(theater);
        }

        // POST: Theaters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var theater = await _context.Theaters.FindAsync(id);
            _context.Theaters.Remove(theater);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TheaterExists(int id)
        {
            return _context.Theaters.Any(e => e.TheaterId == id);
        }

        [HttpGet]
        public IActionResult SignInForTheater()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignInForTheater(Theater theater)
        {
            var userDetails = _context.Theaters.Where(x => x.TheaterName == theater.TheaterName && x.Password == theater.Password).FirstOrDefault();

            if (userDetails == null)
            {
                ModelState.AddModelError("", "Invalid UserName or Password");
                return View("SignInForTheater");
            }
            else
            {
                HttpContext.Session.SetString("TheaterName", userDetails.TheaterName);
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult LogOutForTheater()
        {
            HttpContext.Session.SetString("TheaterName", "");
            return View("SignInForTheater");
        }
    }
}

BookMyTickets/Views/Theaters/Create.cshtml
@model BookMyTickets.Models.Theater

@{
    ViewData["Title"] = "Create";
}
    <style>
        .loginBox {
            box-shadow: 5px 15px rgb(203, 221, 236);
            background-color: rgb(205, 247, 247);
            display: flex;
            flex-direction: column;
            margin: 50px;
            margin-left: 30%;
            margin-right: 30%;
            padding: 50px;
            border-radius: 20px;
            border: none;
            height: auto;
        }
    </style>
    <div class="loginBox">
        <h2>Register For Theater</h2>
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="TheaterName" class="control-label"></label>
                        <input asp-for="TheaterName" class="form-control" />
                        <span asp-validation-for="TheaterName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NoOfScreen" class="control-label"></label>
                        <input asp-for="NoOfScreen" class="form-control" />
                        <span asp-validation-for="NoOfScreen" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="SignUp" class="btn btn-primary" />
                        <a style="margin-left:auto" class="btn btn-primary" name=" value="Go To Login" asp-controller="Theaters" asp-action="SignInForTheater">Go To Login</a>
                    </div>
                </form>
            
      
    </div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BookMyTickets/Views/Theaters/Delete.cshtml
@model BookMyTickets.Models.Theater

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Theater</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TheaterName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TheaterName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoOfScreen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoOfScreen)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TheaterId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookMyTickets/Views/Theaters/Details.cshtml
@model BookMyTickets.Models.Theater

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Theater</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TheaterName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TheaterName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoOfScreen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoOfScreen)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TheaterId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookMyTickets/Views/Theaters/Edit.cshtml
@model BookMyTickets.Models.Theater

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Theater</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TheaterId" />
            <div class="form-group">
                <label asp-for="TheaterName" class="control-label"></label>
                <input asp-for="TheaterName" class="form-control" />
                <span asp-validation-for="TheaterName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoOfScreen" class="control-label"></label>
                <input asp-for="NoOfScreen" class="form-control" />
                <span asp-validation-for="NoOfScreen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BookMyTickets/Views/Theaters/Index.cshtml
@model IEnumerable<BookMyTickets.Models.Theater>

@{
    ViewData["Title"] = "Index";
}
    <style>
        #seeAllTheaters{
            background-color:aliceblue;
        }
    </style>
<h3>List Of All Registered Theater</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TheaterName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoOfScreen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TheaterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoOfScreen)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TheaterId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TheaterId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TheaterId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BookMyTickets/Views/Theaters/SignInForTheater.cshtml
@model Theater
@{
    ViewData["Title"] = "SignInForTheater";
}

<style>
    #navSignInForTheater {
        background-color: aliceblue;
    }

    .loginBox {
        box-shadow: 5px 15px rgb(203, 221, 236);
        background-color: rgb(205, 247, 247);
        display: flex;
        flex-direction: column;
        margin: 50px;
        margin-left: 30%;
        margin-right: 30%;
        /*  text-align: center;
    align-items: center;
    */
        padding: 50px;
        border-radius: 20px;
        border: none;
        height: auto;
    }
</style>

<div class="loginBox">
    <form action="#" method="POST">
        <div>
            <h1>Login For Theater</h1>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TheaterName, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.TheaterName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TheaterName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group" >
        @Html.LabelFor(model => model.Password,htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-15">
            @*@Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" }, @type = "password" })*@

            <input class="form-control text-box single-line" data-val="true" data-val-required="Password is required." id="Password" name="Password" type="password" value="">
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
        <div class="form-group" id="signupLink"><a asp-controller="Theaters" asp-action="Create">New Theater!!Click Here For Registration</a></div>
        <div class="form-group" id="submit"><button type="submit" class="btn btn-primary">Login</button></div>
    </form>
</div>