BookMyTickets/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace BookMyTickets.Models
{
    public class Booking
    {
        [Key]
        public int BookingId { get; set; }

        public int UserId { get; set; }

        public int? ShowId { get; set; }

        public int TotalTickets { get; set; }
        
        public int Seat { get; set; }

    
        public double TotalCost { get; set; }

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "date")]
        public DateTime Date { get; set; }

        public string MovieName { get; set; }

        public string TheaterName { get; set; }

        public string UserName { get; set; }

        public string City { get; set; }

        public int ScreenNo { get; set; }

        public virtual Show Show { get; set; }

        public virtual User User { get; set; }
    }
}

BookMyTickets/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookMyTickets.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net.Mail;
using System.Net;

namespace BookMyTickets.Controllers
{
    public class BookingsController : Controller
    {
        private readonly AppDbContext _context;
        int showId;
        public BookingsController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult payment(IFormCollection fc)
        {
            int seat1 = Int32.Parse(fc["seat"]);
            showId = Int32.Parse(fc["ShowId"]);
            double seatprice= Double.Parse(fc["price"]);
            ViewBag.seat = seat1;
            ViewBag.ShowId = showId;
            ViewBag.price = seatprice*100;
            return View();
        }
            public IActionResult ConfirmBookingPhase4(IFormCollection fc)
        {
            //ViewBag.TotalTickets = fc["TotalTickets"];
            //int totalTickets = Int32.Parse(fc["TotalTickets"]);
            int seat1 = Int32.Parse(fc["seat"]);
         
            int showId = Int32.Parse(fc["ShowId"]);
           
            Booking book = new Booking();
            
                var bookingSeat = _context.Bookings.FirstOrDefault(x => x.ShowId == showId && x.UserName == HttpContext.Session.GetString("UserName") && (x.Seat == seat1));
                if (bookingSeat != null)
                {
                    return RedirectToAction("BookingPhase1", "Shows");
                }
                else
                {
                    book.TotalTickets = 1;
                    book.Seat = seat1;
              

                    book.ShowId = showId;
                    var Show = _context.Shows.FirstOrDefault(x => x.ShowId == showId);
                    var user = _context.Users.FirstOrDefault(x => x.UserName == HttpContext.Session.GetString("UserName"));
                    var movie = _context.Movies.FirstOrDefault(x => x.MovieName == Show.MovieName);
                    book.UserName = HttpContext.Session.GetString("UserName");
                    book.MovieName = Show.MovieName;
                    book.ScreenNo = Show.ScreenNo;
                    book.TheaterName = Show.TheaterName;
                    book.UserId = user.UserId;
                    book.City = Show.City;
                    book.Date = Show.Date;
                if (book.Seat <= 20)
                {
                    string bill = (Show.GoldenPrice).ToString();
                    int bill2 = Int32.Parse(bill);
                    double Cost = (bill2);
                    book.TotalCost = Cost;
                }
                else
                {
                    string bill = (Show.Price).ToString();
                    int bill2 = Int32.Parse(bill);
                    double Cost = (bill2);
                    book.TotalCost = Cost;
                }
                string qr = book.MovieName + ";" + book.ShowId + ";" + book.Seat;
                using (MemoryStream ms = new MemoryStream())
                {
                    QRCodeGenerator qRCodeGenerator = new QRCodeGenerator();
                    QRCodeData qRCodeData = qRCodeGenerator.CreateQrCode(qr, QRCodeGenerator.ECCLevel.Q);
                    QRCode qRCode = new QRCode(qRCodeData);
                    using (Bitmap bitmap=qRCode.GetGraphic(20))
                    {
                        bitmap.Save(ms, ImageFormat.Png);
                        ViewBag.QRCode = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                        try
                        {
                            using (MailMessage mail = new MailMessage())
                            {
                                //mail.From = new MailAddress("aspnetproject43@gmail.com");
                                //mail.To.Add("201710643@ua.edu.lb");
                                //mail.Subject = "Qrcode";
                                ////mail.Body = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                                //mail.Body = "sakasdklasdklasdkl";
                                //using (SmtpClient smtp = new SmtpClient("smtp.gmail.com",587))
                                //{
                                //    smtp.Credentials = new System.Net.NetworkCredential("aspnetproject43@gmail.com", "201710907");
                                //    smtp.EnableSsl = true;
                                //    smtp.Send(mail);
                                //    ViewBag.MovieName = "EmailSent";
                                //}
                               // SmtpClient smtpClient = new SmtpClient("relay-hosting.secureserver.net", 25);

                               // smtpClient.Credentials = new System.Net.NetworkCredential("aspnetproject43@gmail.com", "201710907");
                               // smtpClient.UseDefaultCredentials = true; 
                               // smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
                               // smtpClient.EnableSsl = true;
                                

                               
                               // mail.From = new MailAddress("aspnetproject43@gmail.com", "MyWeb Site");
                               // mail.To.Add(new MailAddress("201710907@ua.edu.lb"));
                               //mail.CC.Add(new MailAddress("MyEmailID@gmail.com"));

                               // smtpClient.Send(mail);

                               
                                    MailMessage msg = new MailMessage();
                                    mail.From = new MailAddress("aspnetproject43@gmail.com");
                                    mail.To.Add("201710643@ua.edu.lb");
                                    mail.Subject = "Qrcode";
                                    mail.Body = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                                    msg.From = new MailAddress("aspnetproject43@gmail.com");
                                    msg.To.Add("Your payment is done");
                                    msg.Body = "Testing the automatic mail";
                                    msg.IsBodyHtml = true;
                                    msg.Subject = "Movie Data";
                                    SmtpClient smt = new SmtpClient("smtp.gmail.com");
                                    smt.Port = 587;
                                    smt.Credentials = new NetworkCredential("aspnetproject43@gmail.com", "MyWeb Site");
                                    smt.EnableSsl = true;
                                    smt.Send(msg);
                                    string script = "<script>alert('Mail Sent Successfully');self.close();</script>";
                            }
                        }
                        catch(Exception ex)
                        {
                            ViewBag.MovieName = Show.MovieName;
                        }
                    }
                }
                
                ViewBag.Url = movie.PosterUrl;
                   // ViewBag.MovieName = movie.MovieName;
                    ViewBag.Language = movie.Language;
                    ViewBag.Genre = movie.Genre;
                    ViewBag.Director = movie.Director;
                    ViewBag.Duretion = movie.Duretion;
                    ViewBag.ReleseDate = movie.ReleaseDate;
                    ViewBag.StartTime = Show.StartTime;
                    ViewBag.Price = Show.Price;
                    _context.Add(book);
                    _context.SaveChanges();
                    return View(book);
                }

            
            
        }

    public IActionResult seatSelectionBookingPhase3(IFormCollection fc)
    {
        ViewBag.ShowId = fc["ShowId"];
        showId = Int32.Parse(fc["ShowId"]);
        var Show = _context.Shows.FirstOrDefault(x => x.ShowId == showId);
        var Movie = _context.Movies.FirstOrDefault(x => x.MovieName == Show.MovieName);
        ViewBag.MovieName = Movie.MovieName;
        ViewBag.Url = Movie.PosterUrl;
        ViewBag.Language = Movie.Language;
        ViewBag.Genre = Movie.Genre;
        ViewBag.Director = Movie.Director;
        ViewBag.Duretion = Movie.Duretion;
        ViewBag.ReleaseDate = Movie.ReleaseDate;
        ViewBag.TheaterName = Show.TheaterName;
        ViewBag.StartTime = Show.StartTime;
        ViewBag.ScreenNo = Show.ScreenNo;
        ViewBag.Date = Show.Date;
        ViewBag.Price = Show.Price;
        ViewBag.GoldenPrice = Show.GoldenPrice;
            var AllseatsRead = _context.Bookings.Where(b => b.ShowId == Show.ShowId).ToList();
            var AllSeats = new List<int>();

            foreach (var s in AllseatsRead)
            {
                AllSeats.Add(s.Seat);
            }
            ViewBag.Allseats = AllSeats;
            return View();
        
        }

        public IActionResult SoldTickets()
        {
            var sold = _context.Bookings.Where(x => x.TheaterName == HttpContext.Session.GetString("TheaterName")).ToList();
            return View(sold);
        }

        public IActionResult BookedTicketsOfUser()
        {
            var booking = _context.Bookings.Where(x => x.UserName == HttpContext.Session.GetString("UserName")).ToList();
            var codes = new List<string>();
            foreach (var book in booking)
            {
                string qr = book.MovieName + ";" + book.ShowId + ";" + book.Seat;
                using (MemoryStream ms = new MemoryStream())
                {
                    QRCodeGenerator qRCodeGenerator = new QRCodeGenerator();

BookMyTickets/Views/Bookings/BookedTicketsOfUser.cshtml
@model IEnumerable<BookMyTickets.Models.Booking>

@{
    ViewData["Title"] = "Index";
}
    <style>
        #navBookingOfUser {
            background-color:aliceblue;
        }
    </style>

    <h2>Booked Tickets</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TotalTickets)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seat)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.TotalCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MovieName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TheaterName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ScreenNo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @*@{ int counter = 1;

                    @foreach (var item in Model)
                    {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalTickets)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seat)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.TotalCost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MovieName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TheaterName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ScreenNo)
                </td>
                <td>


                    <img src="@ViewBag.codes[counter]" style="width:200px;height:200px;" />

                    int counter = counter + 1;
                </td>
            </tr>
        }  }*@

        @{ int i = 0;
            @foreach (var item in Model)
            {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TotalTickets)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Seat)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.TotalCost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MovieName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TheaterName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ScreenNo)
        </td>
        <td>


            <img src="@ViewBag.codes[@i]" style="width:200px;height:200px;" />

           
        </td>
    </tr>
                i = i + 1;
            }  }


    </tbody>
</table>

BookMyTickets/Views/Bookings/ConfirmBookingPhase4.cshtml
@model Booking

<h2>Tickets are Successfully Booked</h2>

<style>
    .page-wrapper,
    .content-wrapper {
        background: #f2f2f2;
        margin: 0;
        padding: 0;
    }

    .content-wrapper {
        margin-top: 1vh;
        margin-bottom: 0vh;
        margin-left: 4vw;
        margin-right: 4vw;
        padding: 2vh 2vw;
    }
</style>


<div class="page-wrapper">
    <div class="content-wrapper">
        <div class="container">
            <div class="row">
                <div class="column">
                    <div class="card" style="width: 18rem;">
                        <img src="@ViewBag.Url" class="card-img-top">
                    </div>
                </div>
                <div class="column">
                    <h2> Movie Name:- @ViewBag.MovieName</h2>
                    <b>Movie Language:-</b>
                    <p>@ViewBag.Language</p>
                    <b>Movie Genre:-</b>
                    <p>@ViewBag.Genre</p>
                    <b>Movie Director:-</b>
                    <p>@ViewBag.Director</p>
                    <b>Movie duration:-</b>
                    <p>@ViewBag.Duretion min.</p>
                    <b>Movie releaseDate:-</b>
                    <p>@ViewBag.ReleaseDate</p>
                </div>
            </div>
        </div>
        <hr />
        <div class="container" style="margin:2rem;">
            <div class="row">
                <table>
                    <tr>
                        <td><b>Show Id:-</b></td>
                        <td>@Model.ShowId</td>

                    </tr>
                    <tr>
                        <td><b>Theater Name:-</b></td>
                        <td>@Model.TheaterName</td>

                    </tr>
                    <tr>
                        <td><b>Screen No:-</b></td>
                        <td>@Model.ScreenNo</td>

                    </tr>
                    <tr>
                        <td><b>Show Starting Time:-</b></td>
                        <td>@ViewBag.StartTime</td>

                    </tr>
                    <tr>
                        <td><b>Show Date:-</b></td>
                        <td>@Model.Date</td>

                    </tr>
                    <tr>
                        <td><b>Price per seat:-</b></td>
                        <td>@ViewBag.Price Rs.</td>

                    </tr>
                    <tr>
                        <td><b>User Name:-</b></td>
                        <td>@Model.UserName</td>

                    </tr>
                    <tr>
                        <td><b>Screen Number:-</b></td>
                        <td>@Model.ScreenNo</td>

                    </tr>
                    <tr>
                        <td><b>Total Ticket(Seat) Booked:-</b></td>
                        <td>@Model.TotalTickets</td>

                    </tr>
                    <tr>
                        <td><b>Seat Number:-</b></td>
                        <td>@Model.Seat</td>

                    </tr>
                   
                    <tr>
                        <td><b>Total Cost:</b></td>
                        <td>@Model.TotalCost</td>

                    </tr>
                    <tr>
                        <td><b>City:-</b></td>
                        <td>@Model.City</td>
                    </tr>
                    <tr>

                        @if (ViewBag.QRCode != null)
                        {
                            <p>QRcode</p>
                            <img src="@ViewBag.QRCode" style="width:200px;height:200px;" />
                        }
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <hr />
    <div></div>
    <hr />

BookMyTickets/Views/Bookings/Create.cshtml
@model BookMyTickets.Models.Booking

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Booking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ShowId" class="control-label"></label>
                <select asp-for="ShowId" class ="form-control" asp-items="ViewBag.ShowId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TotalTickets" class="control-label"></label>
                <input asp-for="TotalTickets" class="form-control" />
                <span asp-validation-for="TotalTickets" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seat" class="control-label"></label>
                <input asp-for="Seat" class="form-control" />
                <span asp-validation-for="Seat" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="TotalCost" class="control-label"></label>
                <input asp-for="TotalCost" class="form-control" />
                <span asp-validation-for="TotalCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieName" class="control-label"></label>
                <input asp-for="MovieName" class="form-control" />
                <span asp-validation-for="MovieName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TheaterName" class="control-label"></label>
                <input asp-for="TheaterName" class="form-control" />
                <span asp-validation-for="TheaterName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScreenNo" class="control-label"></label>
                <input asp-for="ScreenNo" class="form-control" />
                <span asp-validation-for="ScreenNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BookMyTickets/Views/Bookings/Delete.cshtml
@model BookMyTickets.Models.Booking

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalTickets)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalTickets)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Seat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Seat)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MovieName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MovieName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TheaterName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TheaterName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ScreenNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ScreenNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Show)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Show.ShowId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BookingId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookMyTickets/Views/Bookings/seatSelectionBookingPhase3.cshtml
@{
    ViewData["Title"] = "SeatSelectionBookingPhase3";
}

<style>
    .page-wrapper,
    .content-wrapper {
        background: #f2f2f2;
        margin: 0;
        padding: 0;
    }

    .content-wrapper {
        margin-top: 1vh;
        margin-bottom: 0vh;
        margin-left: 4vw;
        margin-right: 4vw;
        padding: 2vh 2vw;
    }
</style>


<div class="page-wrapper">
    <div class="content-wrapper">
        <div class="container">
            <div class="row">
                <div class="column">
                    <div class="card" style="width: 18rem;">
                        <img src="@ViewBag.Url" class="card-img-top">
                    </div>
                </div>
                <div class="column">
                    <h2> Movie Name:- @ViewBag.MovieName</h2>
                    <b>Movie Language:-</b>
                    <p>@ViewBag.Language</p>
                    <b>Movie Genre:-</b>
                    <p>@ViewBag.Genre</p>
                    <b>Movie Director:-</b>
                    <p>@ViewBag.Director</p>
                    <b>Movie duration:-</b>
                    <p>@ViewBag.Duretion min.</p>
                    <b>Movie releaseDate:-</b>
                    <p>@ViewBag.ReleaseDate</p>
                </div>
            </div>
        </div>
        <hr />
        <div class="container" style="margin:2rem;">
           
                    <div class="row">
                        <table>
                            <tr>
                                <td><b>Show Id:-</b></td>
                                <td>@ViewBag.ShowId</td>

                            </tr>
                            <tr>
                                <td><b>Theater Name:-</b></td>
                                <td>@ViewBag.TheaterName</td>

                            </tr>
                            <tr>
                                <td><b>Screen No:-</b></td>
                                <td>@ViewBag.ScreenNo</td>

                            </tr>
                            <tr>
                                <td><b>Show Starting Time:-</b></td>
                                <td>@ViewBag.StartTime</td>

                            </tr>
                            <tr>
                                <td><b>Show Date:-</b></td>
                                <td>@ViewBag.Date</td>

                            </tr>
                            <tr>
                                <td><b>Price per seat:-</b></td>
                                <td>@ViewBag.Price USD.</td>

                            </tr>
                            <tr>
                                <td><b>Price per Goldenseat:-</b></td>
                                <td>@ViewBag.GoldenPrice USD.</td>
                            </tr>
                            
                        </table>
                    </div>
                
        </div>
        <div class="container" style="margin:2rem;">
            @*@using (Html.BeginForm("ConfirmBookingPhase4", "Bookings", FormMethod.Post))
            {*@

        <input type="hidden" value="@ViewBag.ShowId" name="ShowId" /> @*<p>Enter Total No Of Ticket:- </p>
                    @Html.TextBox("TotalTickets")
                    <p>Enter Seat Numer:- </p>
                    @Html.TextBox("Seat");*@

                        <p>Choose a seat to book:</p>
                                        <br>
                                                        @for (int i = 1; i <= 50; i++)
                                                        {
                                                            bool z = false;
                                        @if (ViewBag.Allseats != null)
                                        {
                                            @foreach (var s in ViewBag.Allseats)
                                            {
                                                if (@s == i)
                                                {
                                                    z = true;
                                                }
                                            }
                                                                    @if (z)
                                                                    {
                                                                        <input type="button" style="background-color:red; width:50px;" value="@i" />
                                                                    }
                                                                    else
                                                                    {
                                                                        @**@
        <form asp-action="payment" method="post" style="display:inline;">
            <input type="hidden" name="ShowId" value="@ViewBag.ShowId" />
            @if (i >= 0 && i <= 20)
            {
                <input type="hidden" name="price" value="@ViewBag.GoldenPrice" />
                <button style="background-color:gold; width:50px;" name="seat" type="submit" value="@i">@i</button>
            }
            else
            {
        <input type="hidden" name="price" value="@ViewBag.Price" />
                                    <button style="background-color:blue; width:50px;" name="seat" type="submit" value="@i">@i</button>}


        </form>
                                                                    }
                                        }
                                        @if (@i % 10 == 0)
                                        {
                                            <br />
                                        }
                                                        }


                                                                        <div style="width:500px;height:20px;background-color:aqua;">Screen</div>            
        </div>
    </div>
    <hr />
    <div></div>
    <hr />