BookMyTickets/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookMyTickets.Models;
using Microsoft.AspNetCore.Http;

namespace BookMyTickets.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppDbContext _context;

        public MoviesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> EditMovie()
        {
            return View(await _context.Movies.ToListAsync());
        }

        public async Task<IActionResult> DeleteMovie()
        {
            return View(await _context.Movies.ToListAsync());
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movies.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.MovieId == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MovieId,MovieName,Genre,Description,Language,ReleaseDate,Duretion,Director,Cast,PosterUrl")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MovieId,MovieName,Genre,Description,Language,ReleaseDate,Duretion,Director,Cast,PosterUrl")] Movie movie)
        {
            if (id != movie.MovieId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.MovieId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.MovieId == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.MovieId == id);
        }

        public async Task<IActionResult> movieList()
        {
            return View(await _context.Movies.ToListAsync());
        }

      
        public async Task<IActionResult> search(IFormCollection fc)
        {
            if (HttpContext.Session.GetString("UserName") == null)
            {
                HttpContext.Session.SetString("UserName", "");
            }
            if (HttpContext.Session.GetString("TheaterName") == null)
            {
                HttpContext.Session.SetString("TheaterName", "");
            }
            string s = fc["MovieName"];
            var movies = _context.Movies.Where(m=>m.MovieName.Contains(s));
            return View(await movies.ToListAsync());
        }
    }
}

BookMyTickets/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookMyTickets.Models;
using Microsoft.AspNetCore.Http;

namespace BookMyTickets.Controllers
{
    public class ShowsController : Controller
    {
        private readonly AppDbContext _context;

        public ShowsController(AppDbContext context)
        {
            _context = context;
        }

        
        public IActionResult BookingPhase1(IFormCollection fc)
        {
            if(HttpContext.Session.GetString("UserName") == "")
            {
                return RedirectToAction("SignInForUser", "Users");
            }
            else
            {
                ViewBag.Name = fc["MovieName"];
                string Mname = fc["MovieName"].ToString();
                var movie = _context.Movies.FirstOrDefault(m => m.MovieName == Mname);
                if (movie == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                var shows = _context.Shows.ToList();
                var cities = new List<string>();
               
                foreach(var s in shows)
                {
                    if (cities.Contains(s.City))
                    {

                    }
                    else
                    {
                        cities.Add(s.City);
                    }
                }
                ViewBag.cities = cities;
                
                return View("movieDetailsForBookingPhase1", movie);
            }
        }

        public async Task<IActionResult> AcceptAsync(IFormCollection fc)
        {
            int showId = Int32.Parse(fc["id"]);
            var show = _context.Shows.Where(s => s.ShowId == showId).FirstOrDefault();
            show.accepted = 1;
            _context.Update(show);
            _context.SaveChanges();
            var appDbContext = _context.Shows.Include(s => s.Movie).Include(s => s.Theater);
            return View(await appDbContext.ToListAsync());
        }
            public IActionResult findShowsBookingPhase2(IFormCollection fc)
        {
            string Mname = fc["MovieName"].ToString();
            string city = fc["City"].ToString();
            var movie = _context.Movies.FirstOrDefault(m => m.MovieName == Mname);
            if (movie == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.MovieName = movie.MovieName;
            ViewBag.Genre = movie.Genre;
            ViewBag.Language = movie.Language;
            ViewBag.Duretion = movie.Duretion;
            ViewBag.ReleaseDate = movie.ReleaseDate;
            ViewBag.Director = movie.Director;
            ViewBag.Url = movie.PosterUrl;
            var showDetails = _context.Shows.Where(x => x.MovieName == Mname && x.City == city).ToList();
            return View(showDetails);
        }

        // GET: Shows
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Shows.Include(s => s.Movie).Include(s => s.Theater);
            return View(await appDbContext.ToListAsync());
        }
        

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .Include(s => s.Movie)
                .Include(s => s.Theater)
                .FirstOrDefaultAsync(m => m.ShowId == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // GET: Shows/Create
        public IActionResult Create()
        {
            ViewData["MovieId"] = new SelectList(_context.Movies, "MovieId", "MovieName");
            ViewData["TheaterId"] = new SelectList(_context.Theaters, "TheaterId", "TheaterName");
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MovieId,TheaterId,City,ScreenNo,Date,StartTime,Price,GoldenPrice,Payment")] Show show)
        {
            if (ModelState.IsValid)
            {
                Movie movie = _context.Movies.Where(s => s.MovieId == show.MovieId).FirstOrDefault();
                Theater theater = _context.Theaters.Where(t => t.TheaterId == show.TheaterId).FirstOrDefault();
                show.MovieName = movie.MovieName;
                show.TheaterName = theater.TheaterName;
                show.accepted = 0;
                _context.Add(show);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "MovieId", "MovieName", show.MovieId);
            ViewData["TheaterId"] = new SelectList(_context.Theaters, "TheaterId", "TheaterName", show.TheaterId);
            return View(show);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows.FindAsync(id);
            if (show == null)
            {
                return NotFound();
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "MovieId", "MovieName", show.MovieId);
            ViewData["TheaterId"] = new SelectList(_context.Theaters, "TheaterId", "TheaterName", show.TheaterId);
            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShowId,MovieId,TheaterId,MovieName,TheaterName,City,ScreenNo,Date,StartTime,Price")] Show show)
        {
            if (id != show.ShowId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(show);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowExists(show.ShowId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "MovieId", "MovieName", show.MovieId);
            ViewData["TheaterId"] = new SelectList(_context.Theaters, "TheaterId", "TheaterName", show.TheaterId);
            return View(show);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .Include(s => s.Movie)
                .Include(s => s.Theater)
                .FirstOrDefaultAsync(m => m.ShowId == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var show = await _context.Shows.FindAsync(id);
            _context.Shows.Remove(show);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowExists(int id)
        {
            return _context.Shows.Any(e => e.ShowId == id);
        }
    }
}

BookMyTickets/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BookMyTickets - @ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        html, body {
            height: 100%;
        }
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        header {
            background: #333545;
        }

        #NameOfCompany {
            font-size: x-large;
            color: white;
        }

        #secondary-nav {
            background: #1f2533;
            color: white;
        }

        #primary-nav {
            background: #333545;
            color: white;
        }

        #logo {
            width: 5vw;
            height: 8vh;
        }

        #slider {
            margin: 1vh;
            width: auto;
            height: 320px;
            overflow: hidden;
            position: relative;
            background-color: transparent;
        }

        .page-wrapper,
        .content-wrapper {
            background: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        .content-wrapper {
            margin-top: 1vh;
            margin-bottom: 0vh;
            margin-left: 4vw;
            margin-right: 4vw;
            padding: 2vh 2vw;
        }

        .headingOfContent {
            height: 14vh;
        }

        .list {
            padding-top: 0.6vh;
        }

        .headingList {
            display: inline;
            margin-left: 1vw;
        }


        .selected {
            font-size: large;
            background-color: rgba(243, 194, 194, 0.932);
        }


        button {
            padding: 0.5vh 0.5vw;
            border-color: rgb(199, 198, 198);
            border-radius: 0.7vh;
            -webkit-border-radius: 0.7vh;
            -moz-border-radius: 0.7vh;
            -ms-border-radius: 0.7vh;
            -o-border-radius: 0.7vh;
        }

        footer {
            position: absolute;
            bottom: 0;
            background-color: #333545;
            width: 100%;
            size: 10rem;
            text-align: center;
            line-height: 3rem;
            color: aliceblue;
        }
    </style>
</head>
<body style="height:100%;">
    <header>
        <div id="primary-nav" class="container">
            <div class="row">
                <div class="column col-3 my-3" id="NameOfCompany">
                    <img src="https://i.postimg.cc/g2rLYGT9/favicon.jpg" id="logo">BookMyTickets
                </div>

                <div class="column col-5 my-3" id="search">
                    <form asp-action="search" asp-controller="Movies"method="post">
                        <input type="text" name="MovieName" placeholder="Search Movies By Name... ">
                        <button type="submit">Search</button>
                    </form>
                    
                </div>
                
               
                <div class="column col-2 my-3" id="profile">
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("UserName") != "")
                    {
                        <p>Hello!!..@HttpContextAccessor.HttpContext.Session.GetString("UserName")</p>
                    }
                    else if (@HttpContextAccessor.HttpContext.Session.GetString("TheaterName") != "")
                    {
                        <p>Hello!!..@HttpContextAccessor.HttpContext.Session.GetString("TheaterName")</p>
                    }
                    else
                    { 
                        <p>Hello!!..Guest</p>
                    }
                </div>
            </div>
        </div>
        <div id="secondary-nav">
            <ul class="nav nav-tabs">
                <li class="nav-item" id="navHome">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @if (@HttpContextAccessor.HttpContext.Session.GetString("UserName") == "")
                {
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("TheaterName") == "")
                    {
                        <li class="nav-item" id="navSignInForCustomer">
                            <a class="nav-link" asp-controller="Users" asp-action="SignInForUser">Signin for Customers</a>
                        </li>
                        <li class="nav-item" id="navSignInForTheater">
                            <a class="nav-link" asp-controller="Theaters" asp-action="SignInForTheater">Signin for Theaters</a>
                        </li>
                        <li class="nav-item" id="navAllMovieList">
                            <a class="nav-link" asp-controller="Movies" asp-action="movieList">All Movies List</a>
                        </li>
                        <li class="nav-item" id="navAboutUs">
                            <a class="nav-link" asp-controller="Home" asp-action="AboutUs">AboutUs</a>
                        </li>
                        <li class="nav-item" id="navContactUs">
                            <a class="nav-link" asp-controller="Queries" asp-action="Create">ContactUs</a>
                        </li>
                    }
                }
                @if (@HttpContextAccessor.HttpContext.Session.GetString("UserName").Equals("Admin"))
                {
                    <li class="nav-item" id="addMovie">
                        <a class="nav-link" asp-controller="Movies" asp-action="Create">Add Movie</a>
                    </li>
                    <li class="nav-item" id="EditMovie">
                        <a class="nav-link" asp-controller="Movies" asp-action="EditMovie">Edit Movie</a>
                    </li>
                    <li class="nav-item" id="DeleteMovie">
                        <a class="nav-link" asp-controller="Movies" asp-action="DeleteMovie">Delete Movie</a>
                    </li>
                    <li class="nav-item" id="seeAllUsers">
                        <a class="nav-link" asp-controller="Users" asp-action="Index">See All Users</a>
                    </li>
                    <li class="nav-item" id="seeAllTheaters">
                        <a class="nav-link" asp-controller="Theaters" asp-action="Index">See All Theater</a>
                    </li>
                    <li class="nav-item" id="seeAllBookings">
                        <a class="nav-link" asp-controller="Bookings" asp-action="Index">See All Bookings</a>
                    </li>
                    <li class="nav-item" id="seeAllShows">
                        <a class="nav-link" asp-controller="Shows" asp-action="Index">See All The Shows</a>
                    </li>
                    <li class="nav-item" id="navContactUs">
                        <a class="nav-link" asp-controller="Queries" asp-action="Index">See All Queries</a>
                    </li>
                }

                @if (@HttpContextAccessor.HttpContext.Session.GetString("UserName") != "")
                {
                    @if (!@HttpContextAccessor.HttpContext.Session.GetString("UserName").Equals("Admin"))
                    {
                        <li class="nav-item" id="navAllMovieList">
                            <a class="nav-link" asp-controller="Movies" asp-action="movieList">All Movies List</a>
                        </li>
                        <li class="nav-item" id="navAboutUs">
                            <a class="nav-link" asp-controller="Home" asp-action="AboutUs">AboutUs</a>
                        </li>
                        <li class="nav-item" id="navContactUs">
                            <a class="nav-link" asp-controller="Queries" asp-action="Create">ContactUs</a>
                        </li>
                        <li class="nav-item" id="navBookingOfUser">
                            <a class="nav-link" asp-controller="Bookings" asp-action="BookedTicketsOfUser">Booked Tickets Of @HttpContextAccessor.HttpContext.Session.GetString("UserName")</a>
                        </li>
                        <li class="nav-item" id="navProfile">
                            <a class="nav-link" asp-controller="Users" asp-action="Profile">Profile Of @HttpContextAccessor.HttpContext.Session.GetString("UserName")</a>
                        </li>
                    }
                    <li class="nav-item" id="navSignInForCustomer">
                        <a class="nav-link" asp-controller="Users" asp-action="LogOutForUser">LogOut For @HttpContextAccessor.HttpContext.Session.GetString("UserName")</a>
                    </li>
                }
                @if (@HttpContextAccessor.HttpContext.Session.GetString("TheaterName") != "")
                {
                    <li class="nav-item" id="navAllMovieList">
                        <a class="nav-link" asp-controller="Movies" asp-action="movieList">All Movies List</a>
                    </li>
                    <li class="nav-item" id="navAboutUs">
                        <a class="nav-link" asp-controller="Home" asp-action="AboutUs">AboutUs</a>
                    </li>
                    <li class="nav-item" id="navContactUs">
                        <a class="nav-link" asp-controller="Queries" asp-action="Create">ContactUs</a>
                    </li>
                    <li class="nav-item" id="navAddShow">
                        <a class="nav-link" asp-controller="Shows" asp-action="Create">Add Show In Theater...@HttpContextAccessor.HttpContext.Session.GetString("TheaterName") </a>
                    </li>
                    <li class="nav-item" id="navSold">
                        <a class="nav-link" asp-controller="Bookings" asp-action="SoldTickets">Sold(Booked) Tickets</a>
                    </li>
                    <li class="nav-item" id="navSignInForCustomer">
                        <a class="nav-link" asp-controller="Theaters" asp-action="LogOutForTheater">LogOut For @HttpContextAccessor.HttpContext.Session.GetString("TheaterName")</a>
                    </li>
                }
            </ul>
        </div>
       
    </header>
    
    @RenderBody()
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>